### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nybcouncil** [wdmnybcouncil/national-youth-bike-council#12]
- Add the fact that the Github repo (include the link) should always stay public
- Include a new diagram explaining how the services interact, it does not need to be high-tech, some circles with arrows could work! Just linking the flow of the website together.

**Comment by nybcouncil** [comment]
@5hraddha Let me know if these are showing up under the right repo now :) 


![Image](https://github.com/wdmnybcouncil/national-youth-bike-council/assets/111521908/c04df260-e1c3-43e9-963f-7da42dc36e09)

**Comment by 5hraddha** [comment]
I have added an architecture diagram in our shared document that highlights the flow of the website. I have also added the point that we agreed upon to keep the the GitHub repository of the website as public.

![web-app-architecture](https://github.com/wdmnybcouncil/national-youth-bike-council/assets/27571141/50f4a7a0-b723-43cf-813d-a213c9431f82)
