### ISSUE TITLE
Highlight the 'Join Us' button in the join us page

### ISSUE THREAD

**Issue by nybcouncil** [wdmnybcouncil/national-youth-bike-council#13]
Move the Join Us link above Frequently Asked Questions and convert it into a button like it is header and footer, to highlight it more on the page.

Thank you for this!

**Comment by 5hraddha** [comment]
Done. Have moved the Join Us link above Frequently Asked Questions and converted it into a button like it is header and footer, to highlight it more on the page.

<img width="905" alt="image" src="https://github.com/wdmnybcouncil/national-youth-bike-council/assets/27571141/41851196-2521-43e8-8790-ec579b838e73">

**Comment by 5hraddha** [comment]
Suggestion: Move the link to the top of the page.
