### ISSUE TITLE
Seeing Website Analytics

### ISSUE THREAD

**Issue by nybcouncil** [wdmnybcouncil/national-youth-bike-council#16]
I have not yet looked but am hoping to find a way to see website analytics. We currently use a service called Metricool that enables connecting our site to analytics -- like wise we also can just use a plugin if Strapi has one? 

Putting this one as more important than the other two currently available. Let me know how I can best support, if you need to get into metricool to check it out.

**Comment by 5hraddha** [comment]
https://search.google.com/search-console/welcome

**Comment by 5hraddha** [comment]
https://analytics.google.com/analytics/web/provision/?authuser=0#/provision
