### ISSUE TITLE
Homeroom Allow Non-PDF options

### ISSUE THREAD

**Issue by nybcouncil** [wdmnybcouncil/national-youth-bike-council#7]
I was editing our website last week and noticed that the Homeroom Page was not working. It was not loading because there was one PDF missing from one of the entries. It looks like PDFs are required for that page. I think that makes sense based on what I originally asked for.

I'm thinking that in the future, we may want to link to additional resources, some we may not have a PDF for, like a partner organization's resource or just a social media link that can serve as a Homeroom resource. Would it be possible to not require a PDF but instead, require only one of the four fields to be filled out?

![Image](https://user-images.githubusercontent.com/111521908/238365933-f772dfdd-8ae6-4c41-bd8a-43e9ef1a450c.png)

**Comment by 5hraddha** [comment]
Thanks for reporting the bug! The code was such that it required only one of the four fields to be filled out. But, I was accessing some properties from the pdf that was throwing error when pdf was not provided. So, I have applied a check to access the properties only when pdf is available. So, the bug should be resolved now.
