### ISSUE TITLE
Name of the Links in the Posts

### ISSUE THREAD

**Issue by nybcouncil** [wdmnybcouncil/national-youth-bike-council#8]
To rename the links in the Posts to make them more understandable e.g. 'Post' to 'Media Post'.

![Image](https://user-images.githubusercontent.com/111521908/234451567-f8cdd19c-2624-40c1-923d-d820ddc075c4.png)

**Comment by 5hraddha** [comment]
Have renamed the links in the **Post** to **Media Post** in all the pages:
1. Homeroom
2. Media Coverage 

<img width="1241" alt="image" src="https://github.com/wdmnybcouncil/national-youth-bike-council/assets/27571141/f27843f1-d2c5-4c7d-9f98-eaf84e7eb037">
